services:
  caddy:
    build:
      context: ./config/caddy
    restart: unless-stopped
    environment:
      DOMAIN: ${DOMAIN}
      REDIRECT_SCHEME: ${REDIRECT_SCHEME:-http}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${CADDY_DATA_FOLDER}:/data
      - ${CADDY_CONFIG_FOLDER}:/config
    networks:
      - internal_server_net
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    volumes:
      - ${FILE_BROWSER_SRV_FOLDER}:/srv
      - ${FILE_BROWSER_DATABASE_FOLDER}:/database
      - ${FILE_BROWSER_CONFIG_FOLDER}:/config
    restart: unless-stopped
    networks:
      - internal_server_net
  dns:
    build:
      context: ./config/dns
    environment:
      DOMAIN: ${DOMAIN}
      IP: ${IP}
      UPSTREAM_DNS_1: ${UPSTREAM_DNS_1}
      UPSTREAM_DNS_2: ${UPSTREAM_DNS_2:-8.8.8.8}
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    networks:
      - internal_server_net

networks:
  internal_server_net:
    name: internal_server_net
